<?php

use Illuminate\Database\Seeder;
use App\Models\Integrations\FNC\FNCApprTypes;

class FNCApprTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $appraisalTypes = [
            '0' => 'All - Undetermined',
            '1' => '1004D - Update/Completion',
            '2' => '1004 - URAR',
            '3' => '1004 with 1007',
            '4' => '1004 with 216',
            '5' => '1004 with 216 and 1007',
            '6' => '1004C Manufactured Home',
            '7' => '1007 - Rent Schedule Comp.',
            '8' => '1025 - Sm. Res. Inc.',
            '9' => '1025 with 216',
            '10' => '1073 - Ind. Condo Unit',
            '11' => '1073 with 1007',
            '12' => '1073 with 216',
            '13' => '1073 with 216, 1007',
            '14' => '1075 - Ext. Ind. Condo',
            '15' => '1075 with 1007',
            '16' => '1075 with 216',
            '17' => '1075 with 216, 1007',
            '18' => '2000 - 1 Unit Field Review',
            '19' => '2000A - 2 to 4 Unit Field Review',
            '20' => '2055 Ext with 1007',
            '21' => '2055 Ext with 216',
            '22' => '2055 Ext with 216, 1007',
            '23' => '2055 Exterior Residential',
            '24' => '2070 - Cond and Mkt Report',
            '25' => '2090 - Co-Op Interest',
            '26' => '2095 - Co-Op Ext Interest',
            '27' => '216 - Operating Inc. ',
            '28' => '442 - Satisfactory Certificate',
            '29' => 'Land Appraisal Report',
            '30' => 'Recertification of Value',
            '31' => 'BPO - Interior',
            '32' => 'BPO - Exterior',
            '33' => '2006 - Short Form Review',
            '34' => 'Field Review',
            '35' => 'Desk Review',
            '36' => '2075 - Property Inspection',
            '37' => 'Compliance Inspection Report',
            '38' => 'Desktop Restricted Use Report',
            '39' => 'Photo Only',
            '40' => '2055 Interior',
            '41' => '1007 with 216',
            '42' => 'Computer-Assisted Appraisal',
            '43' => '1004C w/ 216 and 1007',
            '44' => '1025 with 1007',
            '45' => '1025 w/ 216 and 1007',
            '46' => 'Addendum Letter',
            '47' => 'Reassessment of Value',
            '48' => '1004C with 1007',
            '49' => '1004C with 216',
            '50' => 'Construction Draw',
            '51' => 'REO Addendum',
            '52' => 'ERC - Relocation',
            '53' => 'Narrative',
            '54' => 'Commercial',
            '55' => 'Request for Bid',
            '56' => 'FNMA BPO Exterior',
            '57' => 'FNMA BPO Interior',
            '58' => '1004 with REO Addendum',
            '59' => 'FNC BPO - Interior',
            '60' => '2045 - Master Residential Appraisal',
            '61' => 'Appraiser Assisted AVM',
            '62' => 'AVM',
            '63' => 'Third Party Originator Review',
            '64' => '2045A - Master Residential Appraisal - Amendment',
            '65' => 'Other',
            '66' => 'CDNA Service',
            '67' => '1004C with REO Addendum',
            '68' => '1025 with REO Addendum',
            '69' => '1073 with REO Addendum',
            '70' => 'Revision',
            '71' => 'FNC BPO - Exterior',
            '72' => 'PR Sitex',
            '73' => 'HistoryPro',
            '74' => 'Initial Review',
            '75' => '1004 No Cost Approach',
            '76' => '1004 Cost Approach',
            '77' => '1004 No Cost with 6 Month Liquidation Value',
            '78' => '1004D Update',
            '79' => '1004D Completion',
            '80' => 'LoanSafe® CM',
            '81' => 'GeoAVM™',
            '82' => 'External Reconciliation',
            '83' => 'Internal Reconciliation',
            '84' => 'Comp Search',
            '85' => 'Work to Date',
            '86' => 'Partial Inspection Fee',
            '87' => 'Interior Inspection',
            '88' => 'Court Testimony',
            '89' => 'FNMA 2-4 Family Field Review Exterior',
            '90' => 'FNMA 2-4 Family Field Review Interior',
            '91' => 'FNMA One Unit Field Review Exterior',
            '92' => 'FNMA One Unit Field Review Interior',
            '93' => 'Investigative Enhanced Review',
            '94' => 'Investigative Review',
            '95' => 'Investigative Review Following Retrospective Appraisal',
            '96' => 'MLS Data and Assessor Verification',
            '97' => 'Prequalification Analytics',
            '99' => 'Automated Review',
            '100' => 'Correspondent Submission - Lender',
            '101' => 'Correspondent Submission - Investor',
            '102' => 'Title Commitment',
            '103' => 'Flood Basic',
            '104' => 'Flood - Life of Loan',
            '105' => 'Flood - Life of Loan Update ',
            '106' => 'Disaster Inspection',
            '107' => 'Desktop Valuation',
            '108' => 'Commercial Appraisal 1',
            '109' => 'Commercial Appraisal 2',
            '110' => 'Commercial Appraisal 3',
            '111' => 'Commercial Appraisal 4',
            '112' => 'Commercial Appraisal 5',
            '113' => 'Construction Inspection 1',
            '114' => 'Construction Inspection 2',
            '115' => 'Construction Inspection 3',
            '116' => 'Construction Inspection 4',
            '117' => 'Construction Inspection 5',
            '118' => 'Environmental Site Assessment Phase I',
            '119' => 'Environmental Site Assessment Phase I Limited',
            '120' => 'Environmental Site Assessment Phase II',
            '121' => 'Environmental Site Assessment Phase III',
            '122' => 'Environmental Report',
            '123' => 'Consultation 1',
            '124' => 'Transaction Screen 1',
            '125' => 'Consultation 2',
            '126' => 'Transaction Screen 2',
            '127' => 'Consultation 3',
            '128' => 'Database Screen',
            '129' => 'Transaction Screen 3',
            '130' => 'Consultation 4',
            '131' => 'Evaluation 1',
            '132' => 'Evaluation 2',
            '133' => 'Collateral Valuation',
            '134' => 'Service Determination',
        ];

        foreach ($appraisalTypes as $key => $value) {
            FNCApprTypes::updateOrCreate(
                [ 'external_id' => $key ],
                [ 'value' => $value ]
            );
        }
    }
}
